# coding: utf-8

"""
    OpenAPI for NCATS Biomedical Translator Reasoners

    OpenAPI for NCATS Biomedical Translator Reasoners  # noqa: E501

    The version of the OpenAPI document: 0.9.2
    Contact: edeutsch@systemsbiology.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ara_client
from ara_client.models.remote_knowledge_graph import RemoteKnowledgeGraph  # noqa: E501
from ara_client.rest import ApiException


class TestRemoteKnowledgeGraph(unittest.TestCase):
    """RemoteKnowledgeGraph unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoteKnowledgeGraph(self):
        """Test RemoteKnowledgeGraph"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ara_client.models.remote_knowledge_graph.RemoteKnowledgeGraph()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
