# coding: utf-8

"""
    OpenAPI for NCATS Biomedical Translator Reasoners

    OpenAPI for NCATS Biomedical Translator Reasoners  # noqa: E501

    The version of the OpenAPI document: 0.9.2
    Contact: edeutsch@systemsbiology.org
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ara_client
from ara_client.models.node_binding import NodeBinding  # noqa: E501
from ara_client.rest import ApiException


class TestNodeBinding(unittest.TestCase):
    """NodeBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeBinding(self):
        """Test NodeBinding"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ara_client.models.node_binding.NodeBinding()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
