version: '3'

services:

  identifiers:
    build: ./Dockerfile_Identifiers_Server
    ports:
    - "8081:8081"
    networks:
    - default

  ontology:
    build: ./Dockerfile_Jaccard_Similarity_Server
    ports:
    - "8081:5000"
    networks:
    - default

  workflow:
    build: ./Dockerfile_Main
    networks:
    - default

networks:
    default:
        driver: bridge