#
#  NCATS Translator Modules System
#
# This Dockerfile builds a shared base image with the
# NCATS Translator Modules Code already copied over but
# NO dependencies applied yet (due to slight differences
# and possible conflicts in the various component services
# of the complete (Docker Compose) built system

FROM continuumio/miniconda3:4.7.10

# Setting up Docker Conda environment
# Followed advice at https://medium.com/@chadlagore/conda-environments-with-docker-82cdc9d25754

# **** we won't update conda - now (Oct 2019) seems to be problematic
# RUN conda update -n base -c defaults conda

RUN conda create -n translator-modules python=3.7
RUN echo "source activate translator-modules" > ~/.bashrc
ENV PATH /opt/conda/envs/translator-modules/bin:$PATH

# Copying over the core Translator Modules application
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . ./

# Need to install a local copy of the NCATS translator/modules
RUN pip install -e .

# *Temporary* override of pypi Ontobio
RUN pip install -e git+https://github.com/STARInformatics/ontobio.git@goterm_patch#egg=ontobio --no-cache-dir

# Delegating installment of specific service
# dependencies to the applicable child images

CMD ["/bin/bash"]
