#
#  NCATS Translator Modules System
#
# This Dockerfile builds the Docker image to run as a
# Translator Modules Identifiers Resolution Service
#
# To build the image, from the Translator Modules project root directory, type:
#
#    docker build -f Dockerfile_Shared -t translator_modules_shared .
#    docker build -f Dockerfile_Main -t translator_modules .
#
# To start up the Translator Modules container, type:
#
#    docker run -p 8081:8081 translator_modules
#
FROM translator_modules_shared

WORKDIR /usr/src/app

RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate translator-modules && \
    pip install cwlref-runner

ENV PATH /root/.local/bin:$PATH

ENTRYPOINT ["/bin/bash"]
