#
#  NCATS Translator Modules System
#
# This Dockerfile builds the Docker image to run as a
# Translator Modules Ontology Jaccard Similarity Service
#
# To build the image, from the Translator Modules project root directory, type:
#
#    docker build -f Dockerfile_Shared -t translator_modules_shared .
#    docker build -f Dockerfile_Jaccard_Similarity_Server -t jaccard_similarity_server .
#
# To start up the dockerized REST web service container as a daemon process, type:
#
#    docker run -d --rm -p 8082:8082 --memory 3G --name jaccard  jaccard_similarity_server
#
# The REST service web form will be visible on http://0.0.0.0:8082/ui
#
# Note that your Docker Engine / Desktop should be configured to
# support a container memory limit footprint of 3 gigabytes when run
#
# The  resulting server log can be monitored using the command:
#
#    docker logs -f jaccard
#
# Note also that the image from a docker build of this Dockerfile is mainly intended
# to be run as part of the complete ncats/translator-modules docker-compose built system.
#
FROM translator_modules_shared

WORKDIR /usr/src/app/ncats/translator/ontology/server

RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate translator-modules && \
    pip install --no-cache-dir -r requirements.txt

EXPOSE 8082

ENTRYPOINT ["python3"]

CMD ["-m", "openapi_server"]
