# Not sure if this image will suffice for running
# the ncats/translator-modules given the Python 3.7 dependence of the system
# (i.e. miniconda3:4.7.10 may only provide Python 3.5
FROM continuumio/miniconda3:4.7.10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# RUN conda env # create a fresh virtual environment
# RUN conda install python=3.7  #  use Python  3.7 now!

COPY requirements.txt /usr/src/app/

RUN conda install -c anaconda scipy>=1.2.1 numpy=1.16.1 pandas=0.24.2
RUN pip install -r requirements.txt

COPY . /usr/src/app
RUN pip install .

CMD ["/bin/bash"]

