FROM python:3.7

RUN mkdir -p /usr/src

WORKDIR /usr/src

COPY server server
COPY *.whl .

RUN pip install *.whl  && \
    cd server && pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir .

WORKDIR /usr/src/server

EXPOSE 8080

ENTRYPOINT ["python"]

CMD ["-m", "ara_server"]
