#
#  NCATS Translator Modules System
#
# This Dockerfile builds the Docker image to run as a
# Translator Modules Identifiers Resolution Service
#
# To build the image, from the Translator Modules project root directory, type:
#
#    docker build -f Dockerfile_Shared -t translator_modules_shared .
#    docker build -f Dockerfile_Main -t translator_modules .
#
# To start up the Translator Modules container, type:
#
#    docker run -p 8081:8081 translator_modules
#
FROM translator_modules_shared

WORKDIR /usr/src/app

RUN conda install -c anaconda scipy>=1.2.1 numpy=1.16.1 pandas=0.24.2
RUN pip install --no-cache-dir  -r requirements.txt
RUN pip install .

# Point to Docker-Compose network names for microservices
ENV IDENTIFIERS_RESOLUTION_SERVER_HOST http://identifiers:8081
ENV JACCARD_SIMILARITY_SERVER_HOST http://jaccard:8082

ENTRYPOINT [""/bin/bash",  "--login"]
