#
#  NCATS Translator Modules System
#
# This Dockerfile builds a shared base image with the
# NCATS Translator Modules Code already copied over but
# NO dependencies applied yet (due to slight differences
# and possible conflicts in the various component services
# of the complete (Docker Compose) built system

FROM continuumio/miniconda3:4.7.12

# Setting up Docker Conda environment
# Followed advice at https://medium.com/@chadlagore/conda-environments-with-docker-82cdc9d25754

# **** we won't update conda - now (Oct 2019) seems to be problematic
# RUN conda update -n base -c defaults conda

# Application workspace
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN conda create -n translator-modules python=3.7

#  .bashrc will be put into the application workspace?
RUN echo "source conda activate translator-modules" > .bashrc
ENV PATH /opt/conda/envs/translator-modules/bin:/root/.local/bin:$PATH

# Copying over the essential Translator Modules application files
COPY ./ncats ./ncats
COPY ./tests/data ./tests/data
COPY ./cwl ./cwl
COPY ./requirements.txt ./requirements.txt
COPY ./setup.py ./setup.py

# Need gcc for some installations
RUN apt-get -y install gcc

# Need to install a local copy of the NCATS translator/modules project
RUN . /opt/conda/etc/profile.d/conda.sh && \
     conda activate translator-modules && \
     conda install -c anaconda scipy>=1.2.1 numpy=1.16.1 pandas=0.24.2 && \
     pip install --no-cache-dir  -r requirements.txt  && \
     pip install .

# Delegating installment of specific service
# dependencies to the applicable child images
