version: '3'

services:

  ontology:
    build: ncats/translator/ontology
    ports:
      - "8081:5000"
    networks:
        - default

  identifiers:
    build: ncats/translator/identifiers
    ports:
      - "8082:5000"
    networks:
        - default

  workflow:
    build: .
    networks:
        - default

networks:
    default:
        driver: bridge