#
#  NCATS Translator Modules System
#
# This Dockerfile builds the Docker image to run as a
# Translator Modules Ontology Jaccard Similarity Service
#
# To build the image, from the Translator Modules project root directory, type:
#
#    docker build -f Dockerfile_Shared -t translator_modules_shared .
#    docker build -f Dockerfile_Jaccard_Similarity_Server -t jaccard_similarity_server .
#
# To start up the dockerized REST web service container as an individual daemon process, type:
#
#    docker run -d --rm -p 8082:8082 --memory 5G --name jaccard  jaccard_similarity_server
#
# The REST service web form will be visible on http://0.0.0.0:8082/ui
#
# Note that we explicitly suggest a container memory size of 5 gigabytes. This is sufficient for to load the
# Gene Ontology (GO) and Human Phenotype (HP) ontology catalogs into the resulting container. Consult the Docker
# documentation for how to configure your Docker Engine to accommodate this maximum (each OS is distinct for this).
#
# Note that on Mac or Windows, your Docker Engine / Desktop should be configured to
# support a container memory limit footprint of 3 gigabytes when run.
# See the "Resources" preference under https://docs.docker.com/docker-for-mac/
#
# The  resulting server log can be monitored using the command:
#
#    docker logs -f jaccard
#
# Note also that the image from a docker build of this Dockerfile is mainly intended
# to be run as part of the complete ncats/translator-modules docker-compose built system.
#
FROM translator_modules_shared

WORKDIR /usr/src/app/ncats/translator/ontology/server

# Installations include a temporary override of Ontobio
RUN . /opt/conda/etc/profile.d/conda.sh && \
    conda activate translator-modules && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install -e git+https://github.com/biolink/ontobio.git@master#egg=ontobio --no-cache-dir && \
    pip install .

EXPOSE 8082

ENTRYPOINT ["python3"]

CMD ["-m", "openapi_server"]
