version: '3'

services:

  identifiers:
    build: ncats/translator/identifiers/server/openapi_server
    ports:
      - "8081:8081"
    networks:
        - default

#  ontology:
#    build: ncats/translator/ontology/server/openapi_server
#    ports:
#      - "8081:5000"
#    networks:
#        - default

  workflow:
    build: .
    networks:
        - default

networks:
    default:
        driver: bridge