version: '3'

services:

  shared_core_image:
    image: translator_modules_shared
    build:
      context: .
      dockerfile: Dockerfile_Shared

  identifiers:
    build:
      context: .
      dockerfile: Dockerfile_Identifiers_Server
    depends_on:
      - shared_core_image
    ports:
    - "8081:8081"
    networks:
    - default

  jaccard:
    build:
      context: .
      dockerfile: Dockerfile_Jaccard_Similarity_Server
    depends_on:
      - shared_core_image
    ports:
    - "8082:8082"
    networks:
    - default

  workflow:
    build:
          context: .
          dockerfile: Dockerfile_Main
    depends_on:
      - shared_core_image
    networks:
    - default

networks:
    default:
        driver: bridge