FROM python:3.7

RUN mkdir -p /usr/src

WORKDIR /usr/src

COPY server server
COPY client client
COPY ara_server_requirements.txt requirements.txt
COPY ara_setup.py setup.py

RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir .

WORKDIR /usr/src/server

EXPOSE 8080

ENTRYPOINT ["python"]

CMD ["-m", "ara_server"]
