# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.model.base_model_ import Model
from openapi_server.model.computation_id import ComputationId
from openapi_server import util

from openapi_server.model.computation_id import ComputationId  # noqa: E501

class ComputationIdentifier(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, list_identifier=None):  # noqa: E501
        """ComputationIdentifier - a model defined in OpenAPI

        :param list_identifier: The list_identifier of this ComputationIdentifier.  # noqa: E501
        :type list_identifier: ComputationId
        """
        self.openapi_types = {
            'list_identifier': ComputationId
        }

        self.attribute_map = {
            'list_identifier': 'list_identifier'
        }

        self._list_identifier = list_identifier

    @classmethod
    def from_dict(cls, dikt) -> 'ComputationIdentifier':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ComputationIdentifier of this ComputationIdentifier.  # noqa: E501
        :rtype: ComputationIdentifier
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_identifier(self):
        """Gets the list_identifier of this ComputationIdentifier.


        :return: The list_identifier of this ComputationIdentifier.
        :rtype: ComputationId
        """
        return self._list_identifier

    @list_identifier.setter
    def list_identifier(self, list_identifier):
        """Sets the list_identifier of this ComputationIdentifier.


        :param list_identifier: The list_identifier of this ComputationIdentifier.
        :type list_identifier: ComputationId
        """

        self._list_identifier = list_identifier
