# coding: utf-8

"""
    OpenAPI for NCATS Biomedical Translator Reasoners

    OpenAPI for NCATS Biomedical Translator Reasoners  # noqa: E501

    The version of the OpenAPI document: 0.9.2
    Contact: edeutsch@systemsbiology.org
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from ara_client.configuration import Configuration


class RemoteKnowledgeGraph(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'credentials': 'list[Credentials]',
        'protocol': 'str'
    }

    attribute_map = {
        'url': 'url',
        'credentials': 'credentials',
        'protocol': 'protocol'
    }

    def __init__(self, url=None, credentials=None, protocol='neo4j', local_vars_configuration=None):  # noqa: E501
        """RemoteKnowledgeGraph - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._url = None
        self._credentials = None
        self._protocol = None
        self.discriminator = None

        self.url = url
        if credentials is not None:
            self.credentials = credentials
        if protocol is not None:
            self.protocol = protocol

    @property
    def url(self):
        """Gets the url of this RemoteKnowledgeGraph.  # noqa: E501

        URL that provides programmatic access to the remote knowledge graph  # noqa: E501

        :return: The url of this RemoteKnowledgeGraph.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this RemoteKnowledgeGraph.

        URL that provides programmatic access to the remote knowledge graph  # noqa: E501

        :param url: The url of this RemoteKnowledgeGraph.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and url is None:  # noqa: E501
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def credentials(self):
        """Gets the credentials of this RemoteKnowledgeGraph.  # noqa: E501

        Credentials needed for programmatic access to the remote knowledge graph  # noqa: E501

        :return: The credentials of this RemoteKnowledgeGraph.  # noqa: E501
        :rtype: list[Credentials]
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this RemoteKnowledgeGraph.

        Credentials needed for programmatic access to the remote knowledge graph  # noqa: E501

        :param credentials: The credentials of this RemoteKnowledgeGraph.  # noqa: E501
        :type: list[Credentials]
        """

        self._credentials = credentials

    @property
    def protocol(self):
        """Gets the protocol of this RemoteKnowledgeGraph.  # noqa: E501


        :return: The protocol of this RemoteKnowledgeGraph.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this RemoteKnowledgeGraph.


        :param protocol: The protocol of this RemoteKnowledgeGraph.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RemoteKnowledgeGraph):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RemoteKnowledgeGraph):
            return True

        return self.to_dict() != other.to_dict()
