# coding: utf-8

"""
    NCATS Translator Modules Ontology Jaccard Similarity Server

    NCATS Translator Modules Ontology Jaccard Similarity Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.public_api import PublicApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.public_api.PublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_compute_jaccard(self):
        """Test case for compute_jaccard

        post a list of input genes and initiate a Jaccard similarity computation  # noqa: E501
        """
        pass

    def test_get_results(self):
        """Test case for get_results

        Retrieves a list of similarity results when ready   # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
