# coding: utf-8

"""
    NCATS Translator Modules Ontology Jaccard Similarity Server

    NCATS Translator Modules Ontology Jaccard Similarity Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.model.computation_identifier import ComputationIdentifier  # noqa: E501
from openapi_client.rest import ApiException


class TestComputationIdentifier(unittest.TestCase):
    """ComputationIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComputationIdentifier(self):
        """Test ComputationIdentifier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.computation_identifier.ComputationIdentifier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
