# coding: utf-8

"""
    NCATS Translator Modules Ontology Jaccard Similarity Server

    NCATS Translator Modules Ontology Jaccard Similarity Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ncats.translator.ontology.client.openapi_client
from ncats.translator.ontology.client.openapi_client.model.computation_input import ComputationInput  # noqa: E501
from ncats.translator.ontology.client.openapi_client.rest import ApiException


class TestComputationInput(unittest.TestCase):
    """ComputationInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComputationInput(self):
        """Test ComputationInput"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ncats.translator.ontology.client.openapi_client.models.computation_input.ComputationInput()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
