openapi: 3.0.0
servers:
  - description: NCATS Translator Modules Ontology Jaccard Similarity Server
    url: http://0.0.0.0:8082
info:
  description: NCATS Translator Modules Ontology Jaccard Similarity Server
  version: "0.0.1"
  title: NCATS Translator Modules Ontology Jaccard Similarity Server
  contact:
    email: richard@starinformatics.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: public
    description: >
      Operations available to public module users of Ontology Jaccard Similarity computations
paths:
  /compute_jaccard:
    post:
      tags:
        - public
      summary: post a list of input genes and initiate a Jaccard similarity computation
      operationId: compute_jaccard
      description: >
        Post a list of input genes and initiate a Jaccard similarity computation
      responses:
        '201':
          description: >
            Jaccard similarity computation initiated on the server
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputationIdentifier'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: request_body
              $ref: '#/components/schemas/ComputationInput'
        description: >
          List of input genes upon which to compute Jaccard similarity
  /results:
    get:
      tags:
        - public
      summary: >
        Retrieves a list of similarity results when ready
      operationId: get_results
      description: >
        Retrieves a list of similarity results when obtained by a
        Jaccard similarity of a posted list of input genes
      parameters:
        - in: query
          name: computation_id
          description: >
            Computational Identifier UUID returned from a submitted Jaccard similarity
            computation request upon a posted list of input genes
          required: true
          schema:
            type: string
      responses:
        '200':
          description: computation successful, results returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        '102':
          description: >
            The requested computation is still in process without error, but no results are yet available.
        '400':
          description: bad input target parameter
        '404':
          description:  computation not found
components:
  schemas:
    GeneEntry:
      type: object
      required:
        - input_id
        - sim_input_curie
        - input_symbol
      properties:
        input_id: # gene_curie,
          type: string
          example: "HGNC:3583"
        sim_input_curie: # sim_input_curie - not really a curie but seems to be an UniProdKB identifier
          type: string
          example: "UniProtKB:Q8NB91"
        input_symbol: # gene['hit_symbol']
          type: string
          example: "FANCB"
    ComputationInput:
      type: object
      required:
        - ontology
        - input_genes
      properties:
        ontology:
          type: string
          description: >
            Ontology catalog to be queried to compute the Jaccard similarity of input genes
          example: 'go'
        taxon:
          type: string
          description: >
            Taxonomic class of ontology to be used (i.e. human, mouse)
          example: 'human'
        lower_bound:
          type: number
          format: float
          description: >
            Lower bound threshold of Jaccard Similarity scores for similarities returned
        input_genes:
          type: array
          description: >
            List of input genes upon which the Jaccard similarity computation will be applied
          items:
            $ref: '#/components/schemas/GeneEntry'
    ComputationIdentifier:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example:  "123e4567-e89b-12d3-a456-426655440000"
    Terms:
      type: array
      description: >
        Ordered list of term strings (identifiers or names). There should be a one-to-one ordered
        correspondence between the shared_terms and shared_term_names arrays in a given Similarity result entry.
      items:
        type: string
    Similarity:
      type: object
      required:
        - input_id
        - input_symbol
        - hit_symbol
        - hit_id
        - score
        - shared_terms
        - shared_term_names
      properties:
        input_id: # input_gene
          type: string
        input_symbol: # igene['input_symbol']
          type: string
        hit_symbol: # subject_label
          type: string
        hit_id: # subject_curie
          type: string
        score: # score - should this be a numeric data type?
          type: string
        shared_terms:
          type: array
          description: >
            List of shared term identifiers
          items:
            $ref: '#/components/schemas/Terms'
        shared_term_names:
          type: array
          description: >
            List of shared term human readable names
          items:
            $ref: '#/components/schemas/Terms'
    Results:
      type: object
      required:
        - computation_id
        - similarities
      properties:
        computation_id:
          $ref: '#/components/schemas/ComputationIdentifier'
        similarities:
          type: array
          description: >
            List of annotated Jaccard similarity results
          items:
            $ref: '#/components/schemas/Similarity'