openapi: 3.0.0
servers:
  - description: NCATS Translator Modules Ontology Lookup Server
    url: http://0.0.0.0:8082
info:
  description: NCATS Translator Modules Ontology Lookup Server
  version: "0.0.1"
  title: NCATS Translator Modules Ontology Lookup Server
  contact:
    email: richard@starinformatics.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: public
    description: >
      Operations available to public module users of ontology lookup
paths:
  /compute_jaccard:
    post:
      tags:
        - public
      summary: post a list of input genes and initiate a Jaccard similarity computation
      operationId: compute_jaccard
      description: >
        Post a list of input genes and initiate a Jaccard similarity computation
      responses:
        '201':
          description: >
            Jaccard similarity computation initiated on the server
          content:
            application/json:
              schema:
                type: object
                title: ComputationIdentifier
                properties:
                  list_identifier:
                    $ref: '#/components/schemas/ComputationId'
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: request_body
              type: array
              items:
                $ref: '#/components/schemas/GeneEntry'
        description: >
          List of input genes upon which to compute Jaccard similarity
  /results:
    get:
      tags:
        - public
      summary: >
        Retrieves a list of similarity results when ready
      operationId: results
      description: >
        Retrieves a list of similarity results when obtained by a
        Jaccard similarity of a posted list of input genes
      parameters:
        - in: query
          name: compute_id
          description: >
            Computational Identifier UUID from a Jaccard similarity computation
            upon a posted list of input genes
          required: true
          schema:
            type: string
      responses:
        '200':
          description: computation successful, results returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Results'
        '400':
          description: bad input target parameter
components:
  schemas:
    ComputationId:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          example:  "123e4567-e89b-12d3-a456-426655440000"
    GeneEntry:
      type: object
      required:
        - gene_id
      properties:
        input_id: gene_curie,
          type: string
          example: "HGNC:1100"
        sim_input_curie: sim_input_curie,
          type: string
          example: "HGNC:1100"
        input_symbol': gene['hit_symbol']
          type: string
          example: "HGNC:1100"
    Results:
      type: object
      required:
        - computation_id
        - records
      properties:
        computation_id:
          $ref: '#/components/schemas/ComputationId'
        records:
          type: array
          description: >
            list of identifier map entries for every
            identifier registered in the map
          items:
            $ref: '#/components/schemas/Similarity'
    Similarity:
      type: object
      required:
        - 'input_id': input_gene,
          'input_symbol': igene['input_symbol'],
          'hit_symbol': subject_label,
          'hit_id': subject_curie,
          'score': score,
          'shared_terms': shared_terms,
          'shared_term_names': shared_term_names
      properties:
        - 'input_id': input_gene,
          'input_symbol': igene['input_symbol'],
          'hit_symbol': subject_label,
          'hit_id': subject_curie,
          'score': score,
          'shared_terms': shared_terms,
          'shared_term_names': shared_term_names
    Terms:
      type: array
      items:
        type: string