# coding: utf-8

"""
    NCATS Translator Modules Identifier Resolution Server

    NCATS Translator Modules Identifier Resolution Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import ncats.translator.identifiers.client.openapi_client
from ncats.translator.identifiers.client.openapi_client.model.identifier_list_id import IdentifierListId  # noqa: E501
from ncats.translator.identifiers.client.openapi_client.rest import ApiException


class TestIdentifierListId(unittest.TestCase):
    """IdentifierListId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentifierListId(self):
        """Test IdentifierListId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.identifier_list_id.IdentifierListId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
