# coding: utf-8

"""
    NCATS Translator Modules Identifier Resolution Server

    NCATS Translator Modules Identifier Resolution Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest


class TestQueryId(unittest.TestCase):
    """QueryId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueryId(self):
        """Test QueryId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.query_id.QueryId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
