# coding: utf-8

"""
    NCATS Translator Modules Identifier Resolution Server

    NCATS Translator Modules Identifier Resolution Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.public_api import PublicApi  # noqa: E501
from openapi_client.rest import ApiException


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.public_api.PublicApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_identifier_list(self):
        """Test case for identifier_list

        post a list of identifiers  # noqa: E501
        """
        pass

    def test_list_identifier_keys(self):
        """Test case for list_identifier_keys

        list of valid key strings for identifier sources and targets  # noqa: E501
        """
        pass

    def test_translate(self):
        """Test case for translate

        Translates list of identifiers from source to target namespace   # noqa: E501
        """
        pass

    def test_translate_one(self):
        """Test case for translate_one

        translates one identifier source to target namespace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
