# coding: utf-8

"""
    NCATS Translator Modules Identifier Resolution Server

    NCATS Translator Modules Identifier Resolution Server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Contact: richard@starinformatics.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

from ncats.translator.identifiers.client.openapi_client.api.admins_api import AdminsApi  # noqa: E501


class TestAdminsApi(unittest.TestCase):
    """AdminsApi unit test stubs"""

    def setUp(self):
        self.api = AdminsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_load_identifier_map(self):
        """Test case for load_identifier_map

        Identifier Resolver map initial creation  # noqa: E501
        """
        pass

    def test_update_identifier_map(self):
        """Test case for update_identifier_map

        Identifier Resolver map update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
