# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from ncats.translator.identifiers.server.openapi_server.model.base_model_ import Model
from ncats.translator.identifiers.server.openapi_server.model.query_id import QueryId
from ncats.translator.identifiers.server.openapi_server import util

from ncats.translator.identifiers.server.openapi_server.model.query_id import QueryId  # noqa: E501

class IdentifierListId(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, list_identifier=None):  # noqa: E501
        """IdentifierListId - a model defined in OpenAPI

        :param list_identifier: The list_identifier of this IdentifierListId.  # noqa: E501
        :type list_identifier: QueryId
        """
        self.openapi_types = {
            'list_identifier': QueryId
        }

        self.attribute_map = {
            'list_identifier': 'list_identifier'
        }

        self._list_identifier = list_identifier

    @classmethod
    def from_dict(cls, dikt) -> 'IdentifierListId':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IdentifierListId of this IdentifierListId.  # noqa: E501
        :rtype: IdentifierListId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def list_identifier(self):
        """Gets the list_identifier of this IdentifierListId.


        :return: The list_identifier of this IdentifierListId.
        :rtype: QueryId
        """
        return self._list_identifier

    @list_identifier.setter
    def list_identifier(self, list_identifier):
        """Sets the list_identifier of this IdentifierListId.


        :param list_identifier: The list_identifier of this IdentifierListId.
        :type list_identifier: QueryId
        """

        self._list_identifier = list_identifier
